version: "2"

services:

  sdapi_postgres:
    image: postgres:9.6.5
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
      - ./.docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - web
    labels:
      - 'traefik.backend=sdapi_postgres'
      - 'traefik.port=5432'
      - 'traefik.frontend.rule=Host:sdapi_postgres.docker.localhost'

  sdapi_redis:
    image: redis
    networks:
      - web

  sdapi_php:
    image: wodby/php:7.2-4.11.2
    depends_on:
      - sdapi_postgres
    working_dir: /var/www/html
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -Ssdapi_mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - ./:/var/www/html
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    networks:
      - web

  sdapi_web:
    image: wodby/php-nginx:1.13-4.0.0
    depends_on:
      - sdapi_postgres
      - sdapi_php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: sdapi_php
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
      - ./:/var/www/html
    networks:
      web:
        aliases:
          - sd-api.loc
    labels:
      - 'traefik.backend=sdapi_web'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:sdapi.docker.localhost'

  sdapi_mailhog:
    image: mailhog/mailhog
    networks:
      - web
    labels:
      - 'traefik.backend=sdapi_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:sdapi_mailhog.docker.localhost'

networks:
  web:
    external:
      name: traefik_webgateway
